fixtures:
  repositories:
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    profiles: "https://github.com/attachmentgenie/attachmentgenie-profiles.git"
    stacks: "https://github.com/attachmentgenie/attachmentgenie-stacks.git"
  symlinks:
    "roles": "#{source_dir}"
