fixtures:
  repositories:
    stacks: "https://github.com/attachmentgenie/attachmentgenie-stacks.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "roles": "#{source_dir}"
