fixtures:
  forge_modules:
    stdlib: 'puppetlabs/stdlib'
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    profiles: "https://github.com/attachmentgenie/attachmentgenie-profiles.git"
    provision: 'https://github.com/puppetlabs/provision.git'
